//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Connect.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week not recognised.
        /// </summary>
        public static string ERR_DAY_OF_WEEK_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("ERR_DAY_OF_WEEK_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Mode Change.
        /// </summary>
        public static string TXT_ACTIVITY_MODE_CHANGE {
            get {
                return ResourceManager.GetString("TXT_ACTIVITY_MODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string TXT_FRIDAY {
            get {
                return ResourceManager.GetString("TXT_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        public static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string TXT_MONDAY {
            get {
                return ResourceManager.GetString("TXT_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string TXT_SATURDAY {
            get {
                return ResourceManager.GetString("TXT_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string TXT_SUNDAY {
            get {
                return ResourceManager.GetString("TXT_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Default).
        /// </summary>
        public static string TXT_TECHNICIAN_DEFAULT {
            get {
                return ResourceManager.GetString("TXT_TECHNICIAN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string TXT_THURSDAY {
            get {
                return ResourceManager.GetString("TXT_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string TXT_TUESDAY {
            get {
                return ResourceManager.GetString("TXT_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string TXT_WEDNESDAY {
            get {
                return ResourceManager.GetString("TXT_WEDNESDAY", resourceCulture);
            }
        }
    }
}
